#cloud-config
users:
  - name: india
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzugBoyAh99fdD1sX30TxvZzsfrKGG0VntnyeRZTQFC+TvnUSX2Kpq2imUPaDl+FGIaczN6ewAhx27RaRjcA4DnJ6f4L1DhZaMqkAuSSmdeFmYaOPGn/czLsHmGxbgKGdlFQhYNkHmw2gH3svcJ+L54E9ot/xiTpGs4kqXl7+qNPW35eZwodrGkaWoK44iMVAY8stYxO99/2ypgrwNp7sI+1cK4fISFEEqaqb1tgBkNCjJzXgJF8K5kAH/QxyMRQBk8atMcipNju7FKEfz7hkyU/6k0oJXLhAgnxqjdHlCqNCgfvBkrehc7H7iCY8g5NuWSpevAvAFRkXTPSKIFxH9 india@localhost.localdomain

coreos:
  etcd2:
    discovery: "https://discovery.etcd.io/<token>"
    advertise-client-urls: "http://$public_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
  fleet:
    public_ip: "$public_ipv4"
    metadata: role=kubernetes

#hostname: "coreos-host-1"

update:
 reboot-strategy: best-effort
 group: stable
 
write_files:
  - path: "/etc/resolv.conf"
    permissions: "0644"
    owner: root:root
    content: |
     search ayinla.com
     domain ayinla.com
     nameserver 8.8.8.8
     nameserver 8.8.4.4
     
  - path: "/etc/hosts"
    permissions: "0644"
    owner: root:root
    content:  |
      10.0.0.200 openstack.ayinla.com
      10.0.0.109 fedora.ayinla.com
        
