heat_template_version: 2016-10-14
description: create networks 
resources:
  ext-net:
    type: OS::Neutron::ProviderNet
    properties:
      name: ext-net
      network_type: flat
      physical_network: extnet
      router_external: true
      shared: false
  ext-subnet:
    type: OS::Neutron::Subnet
    properties:
      name: ext-subnet
      enable_dhcp: false
      network_id: { get_resource: ext-net }
      cidr: "10.0.0.1/8"
      gateway_ip: 10.0.0.1
      allocation_pools:
        - start: 10.10.10.1
          end: 10.10.10.200
      dns_nameservers: [ "10.1.1.200", "8.8.8.8" ]
      ip_version: 4
  
  int-net:
    type: OS::Neutron::Net
    properties:
      name: int-net
  int-subnet:
    type: OS::Neutron::Subnet
    properties:
      name: int-subnet
      network_id: { get_resource: int-net }
      cidr: "192.168.1.0/24"
      dns_nameservers: [ "10.1.1.200", "8.8.8.8" ]
      ip_version: 4
      enable_dhcp: true
  
  red-net:
    type: OS::Neutron::Net
    properties:
      name: red-net
  red-subnet:
    type: OS::Neutron::Subnet
    properties:
      name: red-subnet
      network_id: { get_resource: red-net }
      cidr: "192.168.2.0/24"
      dns_nameservers: [ "10.1.1.200", "8.8.8.8" ]
      ip_version: 4
      enable_dhcp: true
      
  router1:
    type: OS::Neutron::Router
    properties:
      name: router1
      external_gateway_info: 
        network: {get_resource: ext-net }

  int-net-router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router1 }
      subnet: { get_resource: int-subnet }
   
  red-net-router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router1 }
      subnet: { get_resource: red-subnet }
   
