heat_template_version: 2015-10-15
description: create a server

resources:
      
  inst1:
    type: OS::Nova::Server
    properties:
      name: rhce-server-2
      security_groups:
        - default
      key_name: cloudkey
      flavor: m1.medium
      image: centos-7
      user_data_format: RAW
      user_data:
        get_file: http://10.0.0.109/centos-cloud-config.yml
          
      networks:
        - network: private_network
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: external_network

  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: inst1}
