#cloud-config
users:
  - name: india
    groups:
      - sudo
      - docker
    ssh-authorized-keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzugBoyAh99fdD1sX30TxvZzsfrKGG0VntnyeRZTQFC+TvnUSX2Kpq2imUPaDl+FGIaczN6ewAhx27RaRjcA4DnJ6f4L1DhZaMqkAuSSmdeFmYaOPGn/czLsHmGxbgKGdlFQhYNkHmw2gH3svcJ+L54E9ot/xiTpGs4kqXl7+qNPW35eZwodrGkaWoK44iMVAY8stYxO99/2ypgrwNp7sI+1cK4fISFEEqaqb1tgBkNCjJzXgJF8K5kAH/QxyMRQBk8atMcipNju7FKEfz7hkyU/6k0oJXLhAgnxqjdHlCqNCgfvBkrehc7H7iCY8g5NuWSpevAvAFRkXTPSKIFxH9 india@localhost.localdomain

hostname: "coreos-server-3.ayinla.com"

coreos:
  etcd2:
    discovery: "https://discovery.etcd.io/11131a04c57e763db33004037e96a615"
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://$private_ipv4:2379,http://$private_ipv4:4001,http://127.0.0.1:2379,http://127.0.0.1:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
    
  fleet:
    public-ip: "$private_ipv4"
    metadata: "hostname=coreos-server-3"
    etcd_servers: "http://$private_ipv4:2379,http://127.0.0.1:2379"
      
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
      
update:
 reboot-strategy: best-effort
 group: stable
 
write_files:
  - path: "/etc/resolv.conf"
    permissions: "0644"
    owner: root:root
    content: |
     search ayinla.com
     domain ayinla.com
     nameserver 8.8.8.8
     nameserver 8.8.4.4
     
  - path: "/etc/hosts"
    permissions: "0644"
    owner: root:root
    content:  |
      10.0.0.200 openstack.ayinla.com
      10.0.0.109 fedora.ayinla.com
      
# 127.0.0.1  coreos-server-1.ayinla.com
        
# curl http://169.254.169.254/latest/meta-data/
