#cloud-config
runcmd:
  - sleep 10
  - systemctl daemon-reload
  - systemctl enable etcd.service
  - systemctl enable kube-apiserver
  - systemctl enable kube-controller-manager
  - systemctl enable kube-scheduler
  
write_files:
  - path: /etc/hosts
    owner: root:root
    permissions: '0644'
    content: |
        10.0.0.200 openstack.ayinla.com
        10.0.0.109 fedora.ayinla.com
        127.0.0..1 kube-master
        
  - path: /etc/resolv.conf
    owner: root:root
    permissions: '0644'
    content: |
        search ayinla.com
        domain ayinla.com
        nameserver 8.8.4.4
        nameserver 8.8.8.8
  - path: /run/systemd/system/kube-apiserver.service.d/drop-in.conf
    permissions: '0644'
    content: |
      [Service]
      Environment=KUBE_API_ADDRESS="--address=0.0.0.0"
      Environment=KUBE_API_PORT="--port=8080"
      KUBELET_PORT="--kubelet_port=10250"
      KUBE_ETCD_SERVERS="--etcd_servers=http://127.0.0.1:2379"
      KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"
      KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota"
      KUBE_API_ARGS=""
  
  - path: /run/systemd/system/flanneld.service.d/drop-in.conf
    permissions: '0644'
    content: |
      FLANNEL_ETCD="http://kube-master:4001"
      FLANNEL_ETCD_KEY="/flannel/network"
      #FLANNEL_OPTIONS=""
      
  - path: /run/systemd/system/controller-manager.service.d/drop-in.conf
    permissions: '0644'
    content: |
      [Service]
      KUBELET_ADDRESSES="--machines=kube-minion1, kube-minion2"
      KUBE_CONTROLLER_MANAGER_ARGS=""
      
  - path: /run/systemd/system/etcd.service.d/drop-in.conf
    permissions: '0644'
    owner: root:root
    content: |
      [Service]
      ETCD_NAME=default
      ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
      ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS="http://127.0.0.1:2379"
    
   #- path: /etc/kubernetes/apiserver
  #- path: /etc/kubernetes/config
        
users:
  - name: india
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzugBoyAh99fdD1sX30TxvZzsfrKGG0VntnyeRZTQFC+TvnUSX2Kpq2imUPaDl+FGIaczN6ewAhx27RaRjcA4DnJ6f4L1DhZaMqkAuSSmdeFmYaOPGn/czLsHmGxbgKGdlFQhYNkHmw2gH3svcJ+L54E9ot/xiTpGs4kqXl7+qNPW35eZwodrGkaWoK44iMVAY8stYxO99/2ypgrwNp7sI+1cK4fISFEEqaqb1tgBkNCjJzXgJF8K5kAH/QxyMRQBk8atMcipNju7FKEfz7hkyU/6k0oJXLhAgnxqjdHlCqNCgfvBkrehc7H7iCY8g5NuWSpevAvAFRkXTPSKIFxH9 india@localhost.localdomain
    shell: /bin/bash
package_upgrade: true
packages:
  - epel-release
  - git
  - docker
  - openssl-devel
  - etcd
  - kubernetes
  - flannel
  - vim
  - ntp
  - ruby
  - krb5-workstation
power_state:
  mode: reboot
  
  #/run/systemd/system/fleet.service.d
