#cloud-config
runcmd:
  - yum groupinstall "Development tools" -y
  - systemctl enable haveged; systemctl start haveged
  
write_files:
  - path: /etc/hosts
    owner: root:root
    permissions: '0644'
    content:
      |
        10.0.0.200 openstack.ayinla.com

  - path: /etc/resolv.conf
    owner: root:root
    permissions: '0644'
    content:
      |
        search ayinla.com
        domain ayinla.com
        nameserver 10.0.0.200
        nameserver 8.8.8.8
        
users:
  - name: india
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzugBoyAh99fdD1sX30TxvZzsfrKGG0VntnyeRZTQFC+TvnUSX2Kpq2imUPaDl+FGIaczN6ewAhx27RaRjcA4DnJ6f4L1DhZaMqkAuSSmdeFmYaOPGn/czLsHmGxbgKGdlFQhYNkHmw2gH3svcJ+L54E9ot/xiTpGs4kqXl7+qNPW35eZwodrGkaWoK44iMVAY8stYxO99/2ypgrwNp7sI+1cK4fISFEEqaqb1tgBkNCjJzXgJF8K5kAH/QxyMRQBk8atMcipNju7FKEfz7hkyU/6k0oJXLhAgnxqjdHlCqNCgfvBkrehc7H7iCY8g5NuWSpevAvAFRkXTPSKIFxH9 india@localhost.localdomain
    shell: /bin/bash
package_upgrade: true
packages:
  - epel-release
  - git
  - kernel-devel
  - openssl-devel
  - etcd
  - kubernetes
  - flannel
  - vim
  - ntp
  - ruby
  - wget
  - krb5-workstation
  - pam_krb5
  - haveged
  - rng-tools
  - firewalld.noarch
  - NetworkManager
power_state:
  mode: reboot
